import { randomUUID } from 'node:crypto';
import { AggregateRoot, DomainEvent, Identifier } from '@ados/kernel';
import type { Money } from '@ados/contracts';
import { MARKETING_INTELLIGENCE_EVENTS } from '../events.js';

/** Strongly-typed Marketing Brief identifier. */
export class MarketingBriefId extends Identifier {
  static of(value?: string): MarketingBriefId {
    return new MarketingBriefId(value ?? randomUUID());
  }
}

/**
 * Everything Marketing Intelligence needs to reason about a mission. Passed as a
 * plain DTO — this context never imports another context's aggregates; the
 * caller (or an event handler) assembles it from Client/Brand/Product/Mission.
 */
export interface MarketingContext {
  tenantId: string;
  missionId: string;
  clientId: string;
  clientName: string;
  industry: string;
  brandVoice: string;
  brandValues: string[];
  productName: string;
  productDescription: string;
  missionBrief: string;
  budget?: Money & { period: string };
  /** Deterministic summary of the organization's past campaign performance in this
   * vertical, read from the Company Brain and injected into the prompt as context.
   * It is descriptive history — not a recommendation. */
  historicalPerformance?: string;
}

/** A channel and the share of budget the brief recommends for it. */
export interface BudgetAllocation {
  channel: string;
  percentage: number;
}

/** The strategy the brief recommends. Marketing Intelligence produces strategy
 * and planning ONLY — never ads, images or live campaigns. */
export interface MarketingBriefContent {
  objective: string;
  targetAudience: string;
  positioning: string;
  keyMessages: string[];
  recommendedChannels: string[];
  budgetAllocation: BudgetAllocation[];
  kpis: Array<{ name: string; target: number; unit: string }>;
}

/**
 * Provenance for AI Determinism: which task, model and engine produced this
 * artifact, so it can be replayed and audited. Every AI-generated artifact in
 * AdOS carries one.
 */
export interface AIProvenance {
  taskId: string;
  capability: string;
  model: string;
  engine: string;
  latencyMs: number;
}

export interface MarketingBriefProps {
  tenantId: string;
  missionId: string;
  clientId: string;
  context: MarketingContext;
  content: MarketingBriefContent;
  provenance: AIProvenance;
}

export class MarketingBriefGenerated extends DomainEvent<{
  missionId: string;
  clientId: string;
  objective: string;
  tenantId: string;
}> {
  readonly eventName = MARKETING_INTELLIGENCE_EVENTS.INTEL_BRIEF_GENERATED_V1;
}

/**
 * Marketing Brief — the single output of the Marketing Intelligence sprint. A
 * strategy document generated by the AI Manager from the mission context, with
 * full provenance so it is reproducible.
 */
export class MarketingBrief extends AggregateRoot<MarketingBriefId> {
  private constructor(id: MarketingBriefId, private readonly props: MarketingBriefProps) {
    super(id);
  }

  static generate(input: {
    context: MarketingContext;
    content: MarketingBriefContent;
    provenance: AIProvenance;
    id?: string;
  }): MarketingBrief {
    const brief = new MarketingBrief(MarketingBriefId.of(input.id), {
      tenantId: input.context.tenantId,
      missionId: input.context.missionId,
      clientId: input.context.clientId,
      context: input.context,
      content: input.content,
      provenance: input.provenance,
    });
    brief.addDomainEvent(
      new MarketingBriefGenerated(
        brief.id.toString(),
        {
          missionId: input.context.missionId,
          clientId: input.context.clientId,
          objective: input.content.objective,
          tenantId: input.context.tenantId,
        },
        { tenantId: input.context.tenantId },
      ),
    );
    return brief;
  }

  /** Rehydrate from persistence without emitting events. */
  static restore(id: string, props: MarketingBriefProps): MarketingBrief {
    return new MarketingBrief(MarketingBriefId.of(id), props);
  }

  get tenantId(): string {
    return this.props.tenantId;
  }
  get missionId(): string {
    return this.props.missionId;
  }
  get clientId(): string {
    return this.props.clientId;
  }
  get content(): MarketingBriefContent {
    return this.props.content;
  }
  get provenance(): AIProvenance {
    return this.props.provenance;
  }

  snapshot(): MarketingBriefProps {
    return {
      ...this.props,
      context: { ...this.props.context, brandValues: [...this.props.context.brandValues] },
      content: {
        ...this.props.content,
        keyMessages: [...this.props.content.keyMessages],
        recommendedChannels: [...this.props.content.recommendedChannels],
        budgetAllocation: this.props.content.budgetAllocation.map((b) => ({ ...b })),
        kpis: this.props.content.kpis.map((k) => ({ ...k })),
      },
      provenance: { ...this.props.provenance },
    };
  }
}
