import { randomUUID } from 'node:crypto';
import { AggregateRoot, DomainEvent, Identifier } from '@ados/kernel';
import type { Money } from '@ados/contracts';
import { CAMPAIGN_ENGINE_EVENTS } from '../events.js';

/** Strongly-typed Campaign Draft identifier. */
export class CampaignDraftId extends Identifier {
  static of(value?: string): CampaignDraftId {
    return new CampaignDraftId(value ?? randomUUID());
  }
}

/**
 * Everything the Campaign Engine needs to draft a campaign. A plain DTO
 * assembled from the Marketing Brief and Creative Set — this context never
 * imports another context's aggregates.
 */
export interface CampaignContext {
  tenantId: string;
  missionId: string;
  clientId: string;
  briefId: string;
  creativeSetId: string;
  objective: string;
  targetAudience: string;
  recommendedChannels: string[];
  budgetAllocation: Array<{ channel: string; percentage: number }>;
  totalBudget: Money;
  headline: string;
  adCopy: string;
  cta: string;
}

export interface CampaignAdSet {
  name: string;
  audience: string;
  headline: string;
  primaryText: string;
  cta: string;
}

export interface CampaignChannelPlan {
  channel: string;
  budgetPercentage: number;
  adSets: CampaignAdSet[];
}

/** The draft plan the AI Manager produces. A draft is NEVER launched here —
 * launch is gated on human approval elsewhere. */
export interface CampaignDraftContent {
  name: string;
  objective: string;
  channels: CampaignChannelPlan[];
  schedule: { startHint: string; durationDays: number };
}

/** Provenance for AI Determinism — reproducible/auditable generation. */
export interface AIProvenance {
  taskId: string;
  capability: string;
  model: string;
  engine: string;
  latencyMs: number;
}

export type CampaignDraftStatus = 'draft';

export interface CampaignDraftProps {
  tenantId: string;
  missionId: string;
  clientId: string;
  briefId: string;
  creativeSetId: string;
  totalBudget: Money;
  content: CampaignDraftContent;
  provenance: AIProvenance;
  status: CampaignDraftStatus;
}

export class CampaignCreated extends DomainEvent<{
  missionId: string;
  clientId: string;
  briefId: string;
  creativeSetId: string;
  name: string;
  tenantId: string;
}> {
  readonly eventName = CAMPAIGN_ENGINE_EVENTS.CAMPAIGN_CREATED_V1;
}

/**
 * Campaign Draft — the single output of the Campaign sprint. A structured,
 * approval-ready plan (channels, ad sets, budget split, schedule) generated by
 * the AI Manager. It stays a draft; launching is a separate, human-gated step.
 */
export class CampaignDraft extends AggregateRoot<CampaignDraftId> {
  private constructor(id: CampaignDraftId, private readonly props: CampaignDraftProps) {
    super(id);
  }

  static create(input: {
    context: CampaignContext;
    content: CampaignDraftContent;
    provenance: AIProvenance;
    id?: string;
  }): CampaignDraft {
    const draft = new CampaignDraft(CampaignDraftId.of(input.id), {
      tenantId: input.context.tenantId,
      missionId: input.context.missionId,
      clientId: input.context.clientId,
      briefId: input.context.briefId,
      creativeSetId: input.context.creativeSetId,
      totalBudget: input.context.totalBudget,
      content: input.content,
      provenance: input.provenance,
      status: 'draft',
    });
    draft.addDomainEvent(
      new CampaignCreated(
        draft.id.toString(),
        {
          missionId: input.context.missionId,
          clientId: input.context.clientId,
          briefId: input.context.briefId,
          creativeSetId: input.context.creativeSetId,
          name: input.content.name,
          tenantId: input.context.tenantId,
        },
        { tenantId: input.context.tenantId },
      ),
    );
    return draft;
  }

  /** Rehydrate from persistence without emitting events. */
  static restore(id: string, props: CampaignDraftProps): CampaignDraft {
    return new CampaignDraft(CampaignDraftId.of(id), props);
  }

  get tenantId(): string {
    return this.props.tenantId;
  }
  get missionId(): string {
    return this.props.missionId;
  }
  get briefId(): string {
    return this.props.briefId;
  }
  get creativeSetId(): string {
    return this.props.creativeSetId;
  }
  get totalBudget(): Money {
    return this.props.totalBudget;
  }
  get content(): CampaignDraftContent {
    return this.props.content;
  }
  get provenance(): AIProvenance {
    return this.props.provenance;
  }
  get status(): CampaignDraftStatus {
    return this.props.status;
  }

  snapshot(): CampaignDraftProps {
    return {
      ...this.props,
      totalBudget: { ...this.props.totalBudget },
      content: {
        ...this.props.content,
        schedule: { ...this.props.content.schedule },
        channels: this.props.content.channels.map((c) => ({
          ...c,
          adSets: c.adSets.map((a) => ({ ...a })),
        })),
      },
      provenance: { ...this.props.provenance },
    };
  }
}
