import { randomUUID } from 'node:crypto';
import { AggregateRoot, DomainEvent, Identifier } from '@ados/kernel';
import { EXECUTIVE_AI_EVENTS } from '../events.js';

/** Strongly-typed Executive Report identifier. */
export class ExecutiveReportId extends Identifier {
  static of(value?: string): ExecutiveReportId {
    return new ExecutiveReportId(value ?? randomUUID());
  }
}

/**
 * Everything the CEO needs to synthesize a mission into an executive view. A
 * plain DTO assembled from the Mission, Marketing Brief and Campaign Report —
 * this context never imports another context's aggregates.
 */
export interface ExecutiveContext {
  tenantId: string;
  missionId: string;
  clientId: string;
  clientName: string;
  missionBrief: string;
  objective: string;
  reportId: string;
  kpis: Array<{ name: string; value: number; unit: string }>;
  reportSummary: string;
  reportRecommendations: string[];
}

export type MissionVerdict = 'exceeded' | 'on_track' | 'at_risk';

export interface KeyResult {
  metric: string;
  value: number;
  unit: string;
  verdict: string;
}

/** The CEO Dashboard — the executive synthesis of the whole mission. */
export interface DashboardContent {
  headline: string;
  executiveSummary: string;
  verdict: MissionVerdict;
  keyResults: KeyResult[];
  decisions: string[];
  nextActions: string[];
}

/** Provenance for AI Determinism — reproducible/auditable generation. */
export interface AIProvenance {
  taskId: string;
  capability: string;
  model: string;
  engine: string;
  latencyMs: number;
}

export interface ExecutiveReportProps {
  tenantId: string;
  missionId: string;
  clientId: string;
  reportId: string;
  context: ExecutiveContext;
  content: DashboardContent;
  provenance: AIProvenance;
}

export class DashboardGenerated extends DomainEvent<{
  missionId: string;
  clientId: string;
  reportId: string;
  verdict: MissionVerdict;
  tenantId: string;
}> {
  readonly eventName = EXECUTIVE_AI_EVENTS.EXEC_DASHBOARD_GENERATED_V1;
}

/**
 * Executive Report (CEO Dashboard) — the single, final output of the demo flow.
 * The CEO synthesizes the mission, brief and campaign report into a headline
 * verdict, key results, decisions and next actions, generated by the AI Manager
 * with provenance so it is reproducible.
 */
export class ExecutiveReport extends AggregateRoot<ExecutiveReportId> {
  private constructor(id: ExecutiveReportId, private readonly props: ExecutiveReportProps) {
    super(id);
  }

  static generate(input: {
    context: ExecutiveContext;
    content: DashboardContent;
    provenance: AIProvenance;
    id?: string;
  }): ExecutiveReport {
    const report = new ExecutiveReport(ExecutiveReportId.of(input.id), {
      tenantId: input.context.tenantId,
      missionId: input.context.missionId,
      clientId: input.context.clientId,
      reportId: input.context.reportId,
      context: input.context,
      content: input.content,
      provenance: input.provenance,
    });
    report.addDomainEvent(
      new DashboardGenerated(
        report.id.toString(),
        {
          missionId: input.context.missionId,
          clientId: input.context.clientId,
          reportId: input.context.reportId,
          verdict: input.content.verdict,
          tenantId: input.context.tenantId,
        },
        { tenantId: input.context.tenantId },
      ),
    );
    return report;
  }

  /** Rehydrate from persistence without emitting events. */
  static restore(id: string, props: ExecutiveReportProps): ExecutiveReport {
    return new ExecutiveReport(ExecutiveReportId.of(id), props);
  }

  get tenantId(): string {
    return this.props.tenantId;
  }
  get missionId(): string {
    return this.props.missionId;
  }
  get reportId(): string {
    return this.props.reportId;
  }
  get content(): DashboardContent {
    return this.props.content;
  }
  get verdict(): MissionVerdict {
    return this.props.content.verdict;
  }
  get provenance(): AIProvenance {
    return this.props.provenance;
  }

  snapshot(): ExecutiveReportProps {
    return {
      ...this.props,
      context: {
        ...this.props.context,
        kpis: this.props.context.kpis.map((k) => ({ ...k })),
        reportRecommendations: [...this.props.context.reportRecommendations],
      },
      content: {
        ...this.props.content,
        keyResults: this.props.content.keyResults.map((k) => ({ ...k })),
        decisions: [...this.props.content.decisions],
        nextActions: [...this.props.content.nextActions],
      },
      provenance: { ...this.props.provenance },
    };
  }
}
