import { randomUUID } from 'node:crypto';
import { AggregateRoot, DomainEvent, Identifier } from '@ados/kernel';
import { CREATIVE_STUDIO_EVENTS } from '../events.js';

/** Strongly-typed Creative Set identifier. */
export class CreativeSetId extends Identifier {
  static of(value?: string): CreativeSetId {
    return new CreativeSetId(value ?? randomUUID());
  }
}

/**
 * Everything the Creative Studio needs to write copy. A plain DTO assembled from
 * the Marketing Brief — this context never imports another context's aggregates.
 * The Creative Studio produces copy ONLY; it never touches campaigns or ad
 * platforms.
 */
export interface CreativeContext {
  tenantId: string;
  missionId: string;
  clientId: string;
  briefId: string;
  productName: string;
  brandVoice: string;
  objective: string;
  targetAudience: string;
  positioning: string;
  keyMessages: string[];
  /** Brand identity of the mission's brand — used by the brand-safety gate. */
  brandId?: string;
  /** Operator-defined words the generated copy must never contain. */
  bannedWords?: string[];
}

export interface LandingPageCopy {
  headline: string;
  body: string;
  cta: string;
}

export interface EmailCopy {
  subject: string;
  body: string;
}

/** The six creative outputs of the sprint. */
export interface CreativeContent {
  headline: string;
  adCopy: string;
  cta: string;
  socialPost: string;
  landingPage: LandingPageCopy;
  email: EmailCopy;
}

/** Provenance for AI Determinism — reproducible/auditable generation. */
export interface AIProvenance {
  taskId: string;
  capability: string;
  model: string;
  engine: string;
  latencyMs: number;
}

export interface CreativeSetProps {
  tenantId: string;
  missionId: string;
  clientId: string;
  briefId: string;
  context: CreativeContext;
  content: CreativeContent;
  provenance: AIProvenance;
}

export class CreativeGenerated extends DomainEvent<{
  missionId: string;
  clientId: string;
  briefId: string;
  headline: string;
  tenantId: string;
}> {
  readonly eventName = CREATIVE_STUDIO_EVENTS.CREATIVE_GENERATED_V1;
}

/** Emitted when the brand-safety gate blocks generated copy before it is saved. */
export class CreativeBlocked extends DomainEvent<{
  missionId: string;
  clientId: string;
  briefId: string;
  issues: string[];
  tenantId: string;
}> {
  readonly eventName = CREATIVE_STUDIO_EVENTS.CREATIVE_BLOCKED_V1;
}

/**
 * Creative Set — the single output of the Creative Studio sprint. Ad copy,
 * headline, CTA, social post, landing page and email, generated by the AI
 * Manager from the brief, with full provenance.
 */
export class CreativeSet extends AggregateRoot<CreativeSetId> {
  private constructor(id: CreativeSetId, private readonly props: CreativeSetProps) {
    super(id);
  }

  static generate(input: {
    context: CreativeContext;
    content: CreativeContent;
    provenance: AIProvenance;
    id?: string;
  }): CreativeSet {
    const set = new CreativeSet(CreativeSetId.of(input.id), {
      tenantId: input.context.tenantId,
      missionId: input.context.missionId,
      clientId: input.context.clientId,
      briefId: input.context.briefId,
      context: input.context,
      content: input.content,
      provenance: input.provenance,
    });
    set.addDomainEvent(
      new CreativeGenerated(
        set.id.toString(),
        {
          missionId: input.context.missionId,
          clientId: input.context.clientId,
          briefId: input.context.briefId,
          headline: input.content.headline,
          tenantId: input.context.tenantId,
        },
        { tenantId: input.context.tenantId },
      ),
    );
    return set;
  }

  /** Rehydrate from persistence without emitting events. */
  static restore(id: string, props: CreativeSetProps): CreativeSet {
    return new CreativeSet(CreativeSetId.of(id), props);
  }

  get tenantId(): string {
    return this.props.tenantId;
  }
  get missionId(): string {
    return this.props.missionId;
  }
  get briefId(): string {
    return this.props.briefId;
  }
  get content(): CreativeContent {
    return this.props.content;
  }
  get provenance(): AIProvenance {
    return this.props.provenance;
  }

  snapshot(): CreativeSetProps {
    return {
      ...this.props,
      context: { ...this.props.context, keyMessages: [...this.props.context.keyMessages] },
      content: {
        ...this.props.content,
        landingPage: { ...this.props.content.landingPage },
        email: { ...this.props.content.email },
      },
      provenance: { ...this.props.provenance },
    };
  }
}
